# name: Deploy to Server

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy to Server via SSH
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /path/to/your/project
#             git pull origin master
#             # 필요 시 추가 명령어 (예: 의존성 설치, 서버 재시작)
#             sudo systemctl restart your-web-service
